<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
       <TargetFramework>net10.0</TargetFramework>
		<ApplicationIcon>app.ico</ApplicationIcon>
		<StartupObject />
		<AssemblyName>Pix2d</AssemblyName>
		<EnableAvaloniaXamlCompilation>false</EnableAvaloniaXamlCompilation>
		<Version>$(Pix2dVersion)</Version>
		<PackageProjectUrl>https://pix2d.com</PackageProjectUrl>
    
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>false</SelfContained>
		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
		<RuntimeIdentifiers>win-x64;win-arm64;osx-arm64;osx-x64;linux-x64;linux-arm64;</RuntimeIdentifiers>
		<UseSubFolderForOutputDirDuringMultiPlatformBuild>false</UseSubFolderForOutputDirDuringMultiPlatformBuild>
		<IsWindows Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">true</IsWindows>
		<IsOSX Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' == 'true'">true</IsOSX>
		<IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<PublishTrimmed>false</PublishTrimmed>
		<TrimMode>link</TrimMode>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
	</PropertyGroup>
	<ItemGroup>
		<TrimmerRootDescriptor Include="LinkerConfig.xml" />
	</ItemGroup>
	<PropertyGroup Condition="'$(IsWindows)'=='true'">
		<DefineConstants>Windows</DefineConstants>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
	</PropertyGroup>
	<PropertyGroup Condition="'$(IsOSX)'=='true'">
		<DefineConstants>OSX</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(IsLinux)'=='true'">
		<DefineConstants>Linux</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(IsOSX)'=='true'">
		<CFBundleName>Pix2d</CFBundleName>
		<!-- Also defines .app file name -->
		<CFBundleDisplayName>Pix2d</CFBundleDisplayName>
		<CFBundleIdentifier>com.pix2d.app</CFBundleIdentifier>
		<CFBundleVersion>$(Pix2dVersion)</CFBundleVersion>
		<CFBundleShortVersionString>$(Pix2dVersion)</CFBundleShortVersionString>
		<CFBundlePackageType>APPL</CFBundlePackageType>
		<!--<CFBundleSignature>????</CFBundleSignature>-->
		<CFBundleExecutable>Pix2d</CFBundleExecutable>
		<CFBundleIconFile>Pix2d.png</CFBundleIconFile>
		<!-- Will be copied from output directory -->
		<NSPrincipalClass>NSApplication</NSPrincipalClass>
		<NSHighResolutionCapable>true</NSHighResolutionCapable>
		<UseAppHost>true</UseAppHost>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<RunAOTCompilation>true</RunAOTCompilation>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
		<PlatformTarget>x64</PlatformTarget>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">
		<PlatformTarget>ARM64</PlatformTarget>
		<RuntimeIdentifier>win-arm64</RuntimeIdentifier>
	</PropertyGroup>
	<ItemGroup>
		<Compile Update="**\*.xaml.cs">
			<DependentUpon>%(Filename)</DependentUpon>
		</Compile>
		<AvaloniaResource Include="**\*.xaml">
			<SubType>Designer</SubType>
		</AvaloniaResource>
	</ItemGroup>
	<ItemGroup>
	  <AvaloniaResource Remove="artifacts\**" />
	  <AvaloniaXaml Remove="artifacts\**" />
	  <Compile Remove="artifacts\**" />
	  <EmbeddedResource Remove="artifacts\**" />
	  <None Remove="artifacts\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.0.1" />
		<PackageReference Include="Avalonia.Desktop" Version="12.0.1" />
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1" />
		<PackageReference Include="Clowd.Clipboard" Version="1.1.4" />
		<PackageReference Include="Clowd.Clipboard.Gdi" Version="1.1.4" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Tmds.DBus.Protocol" Version="0.92.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Core\Pix2d.Shared\Pix2d.Shared.csproj" />
		<ProjectReference Include="..\..\Core\Pix2d.Core\Pix2d.Core.csproj" />
		<ProjectReference Include="..\..\Plugins\FormatSupport\Psd\Pix2d.Plugins.Psd\Pix2d.Plugins.Psd.csproj" />
		<ProjectReference Include="..\..\Plugins\Pix2d.Plugins.Ai\Pix2d.Plugins.Ai.csproj" />
	</ItemGroup>
</Project>