<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
       <TargetFramework>net10.0</TargetFramework>
		<RootNamespace>Pix2d</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="AboutAssets.txt" />
	</ItemGroup>
	<ItemGroup>
		<AvaloniaResource Include="AboutAssets.txt" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="SkiaSharp" Version="3.119.4" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Pix2d.Infrastructure\Pix2d.Infrastructure.csproj" />
		<ProjectReference Include="..\SkiaNodes\SkiaNodes.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Using Include="Pix2d.Abstract.State" />
	</ItemGroup>

</Project>