<Project>
	<PropertyGroup>
		<Nullable>enable</Nullable>
		<Pix2dAndroidVersion>104</Pix2dAndroidVersion>
		<Pix2dVersion>3.11.5</Pix2dVersion>
		<Platforms>AnyCPU;x64;ARM64</Platforms>
	</PropertyGroup>

	<!--Used for display version in GitHub Actions when building release-->
	<Target Name="GetPix2dVersion">
    	<Message Text="Pix2dVersion: $(Pix2dVersion)" Importance="high" />
  	</Target>
</Project>
