name: Windows Store MSIX Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'App version (format: 3.3.3.0)'
        required: false
        default: ''
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    env:
      SOLUTION_NAME: Sources/Pix2d.sln
      WAP_PROJECT_DIR: Sources/Heads/Pix2d.Desktop.Wap
      WAP_PROJECT_PATH: Sources/Heads/Pix2d.Desktop.Wap/Pix2d.Desktop.Wap.wapproj
      CONFIGURATION: Release

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2.0.0

    - name: Determine App Version
      id: get_version
      shell: pwsh
      run: |
        # Default version
        $version = ""

        # If triggered by tag, extract version from tag (e.g., v3.3.3 -> 3.3.3.0)
        if ($env:GITHUB_REF -like 'refs/tags/v*') {
          $tag = $env:GITHUB_REF -replace 'refs/tags/v', ''
          if ($tag -match '^\d+\.\d+\.\d+$') {
            $version = "$tag.0"
          }
        }

        # If triggered manually and input is provided, use it
        if ("${{ github.event_name }}" -eq "workflow_dispatch" -and "${{ github.event.inputs.version }}") {
          $version = "${{ github.event.inputs.version }}"
        }

        # Fallback if still empty
        if (-not $version) {
          $version = "0.0.0.0"
        }

        echo "Using version: $version"
        echo "APP_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Patch AppxManifest version
      shell: pwsh
      run: |
        $manifestPath = "$env:WAP_PROJECT_DIR/Package.appxmanifest"
        Write-Host "Patching manifest at $manifestPath with version ${{ env.APP_VERSION }}"

        # Read the entire file content as a raw string
        $originalContent = [System.IO.File]::ReadAllText($manifestPath)

        # Perform the replacement. Use backticks for escaping quotes within the string.
        $newContent = $originalContent -replace 'Version="[^"]*"', "Version=`"${{ env.APP_VERSION }}`""

        # Write the content back using UTF8 encoding without a Byte Order Mark (BOM)
        [System.IO.File]::WriteAllText($manifestPath, $newContent, (New-Object System.Text.UTF8Encoding($false)))
        Write-Host "Manifest patched successfully."

    - name: Restore NuGet packages
      run: msbuild $env:WAP_PROJECT_PATH /t:Restore /p:Configuration=$env:CONFIGURATION /p:IsWAPHeadProject=true

    - name: Decode signing certificate
      shell: pwsh
      run: |
        $certBytes = [Convert]::FromBase64String("${{ secrets.BASE64_ENCODED_PFX }}")
        $certPath = Join-Path -Path $env:WAP_PROJECT_DIR -ChildPath 'certificate.pfx'
        [IO.File]::WriteAllBytes($certPath, $certBytes)

    - name: Build MSIX package
      shell: pwsh
      run: |
        msbuild $env:WAP_PROJECT_PATH `
          /p:IsWAPHeadProject=true `
          /p:Configuration=$env:CONFIGURATION `
          /p:AppxBundle=Always `
          /p:UapAppxPackageBuildMode=StoreUpload `
          /p:AppxBundlePlatforms="x86|x64|arm64" `
          /p:PackageCertificateKeyFile="$env:WAP_PROJECT_DIR/certificate.pfx" `
          # /p:PackageCertificatePassword="${{ secrets.PFX_KEY }}"

    - name: Remove signing certificate
      shell: pwsh
      run: Remove-Item -Path "$env:WAP_PROJECT_DIR/certificate.pfx" -Force

    - name: Zip AppPackages output
      shell: pwsh
      run: |
        $source = "${{ env.WAP_PROJECT_DIR }}/AppPackages"
        $destination = "${{ env.WAP_PROJECT_DIR }}/msix-package.zip"
        if (Test-Path $destination) { Remove-Item $destination -Force }
        Compress-Archive -Path "$source\*" -DestinationPath $destination

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: msix-package
        path: ${{ env.WAP_PROJECT_DIR }}/msix-package.zip
        retention-days: 7

  upload-to-store:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: msix-package
        path: ./artifacts

    - name: Unzip downloaded package
      shell: pwsh
      run: |
        Expand-Archive -Path ./artifacts/msix-package.zip -DestinationPath ./artifacts -Force

    - name: Setup PowerShell environment
      shell: pwsh
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force

        Install-Module -Name StoreBroker -Force -AllowClobber -Scope AllUsers

        Import-Module StoreBroker -Force

        Get-Command -Module StoreBroker

    - name: Upload to Microsoft Store
      shell: pwsh
      env:
        TENANT_ID: ${{ secrets.TENANT_ID }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        PRODUCT_ID: ${{ secrets.PRODUCT_ID }}
      run: |
        $VerbosePreference = "Continue"

        if (-not (Get-Module -ListAvailable -Name StoreBroker)) {
            Install-PackageProvider -Name NuGet -Force
            Install-Module -Name StoreBroker -Force -AllowClobber
        }

        Import-Module StoreBroker -Force

        $packagePath = Get-ChildItem -Path ./artifacts -Filter *.msixupload -Recurse -ErrorAction Stop | Select-Object -First 1
        if (-not $packagePath) { throw ".msixupload package not found" }

        try {
            # Use CLIENT_SECRET to create secure string for credential
            $secureSecret = ConvertTo-SecureString $env:CLIENT_SECRET -AsPlainText -Force
            $credential = New-Object System.Management.Automation.PSCredential($env:CLIENT_ID, $secureSecret)

            Write-Host "Authenticating..."
            Set-StoreBrokerAuthentication -TenantId $env:TENANT_ID -Credential $credential -Verbose

            Write-Host "Creating new submission..."
            try {
              $submission = New-ApplicationSubmission -AppId $env:PRODUCT_ID -Verbose
            } catch {
              Write-Error "Cannot create submission. Check if there's an in-progress submission created manually via the Partner Center."
              Write-Error $_.Exception.ToString()
              throw
            }

            if (-not $submission.fileUploadUrl) {
                throw "fileUploadUrl is empty. Cannot proceed with uploading the package."
            }
            $uploadUrl = $submission.fileUploadUrl

            Write-Host "Adding package to submission..."
            Set-SubmissionPackage -PackagePath $packagePath.FullName -UploadUrl $uploadUrl

            if ($env:GITHUB_EVENT_NAME -eq "workflow_dispatch") {
                Write-Host "Skipping Complete-ApplicationSubmission because this run was triggered manually (workflow_dispatch). Review the submission in Partner Center."
            } else {
                Write-Host "Completing submission..."
                Complete-ApplicationSubmission -AppId $env:PRODUCT_ID -SubmissionId $submission.Id
            }

            Write-Host "Success!"
        }
        catch {
            Write-Error "Failed: $_"
            exit 1
        }
