# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    Project_Path: Sources\PlatformHeads\Desktop\Pix2d.Desktop.Windows\Pix2d.Desktop.Windows.csproj                        # Replace with your solution name, i.e. MyWpfApp.sln.
    
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore $env:Project_Path
    - name: Build
      run: dotnet build --no-restore $env:Project_Path
    - name: Test
      run: dotnet test --no-build --verbosity normal $env:Project_Path
    - name: publish x64
      run: dotnet publish -c Release -r x64 --sc true -o C:\tmp\pix2dAv
    # - name: Building the installer
    #   run: |
    #     "%programfiles(x86)%\Inno Setup 6\iscc.exe" "FreenetInstall_InnoSetup.iss"
    #   shell: cmd
